config/routes.rb
Rails.application.routes.draw do
 
  resources :line_items
  resources :carts
  resources :passagems
  devise_for :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :aerotransportes
  
  root 'aerotransportes#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/passagem.rb
class Passagem < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  belongs_to :Aerotransporte
  has_many :line_items

  private 
  def not_referenced_by_any_line_item
    unless line_items.empty? 
      erros.add(:base, "Line items present")
      throw :abort
    end
  end
end

app/controllers/passagems_controller.rb
class PassagemsController < ApplicationController
  before_action :set_passagem, only: [:show, :edit, :update, :destroy]

  # GET /passagems
  # GET /passagems.json
  def index
    @passagems = Passagem.all
  end

  # GET /passagems/1
  # GET /passagems/1.json
  def show
  end

  # GET /passagems/new
  def new
    @passagem = Passagem.new
  end

  # GET /passagems/1/edit
  def edit
  end

  # POST /passagems
  # POST /passagems.json
  def create
    @passagem = Passagem.new(passagem_params)

    respond_to do |format|
      if @passagem.save
        format.html { redirect_to @passagem, notice: 'Passagem was successfully created.' }
        format.json { render :show, status: :created, location: @passagem }
      else
        format.html { render :new }
        format.json { render json: @passagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passagems/1
  # PATCH/PUT /passagems/1.json
  def update
    respond_to do |format|
      if @passagem.update(passagem_params)
        format.html { redirect_to @passagem, notice: 'Passagem was successfully updated.' }
        format.json { render :show, status: :ok, location: @passagem }
      else
        format.html { render :edit }
        format.json { render json: @passagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passagems/1
  # DELETE /passagems/1.json
  def destroy
    @passagem.destroy
    respond_to do |format|
      format.html { redirect_to passagems_url, notice: 'Passagem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passagem
      @passagem = Passagem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passagem_params
      params.require(:passagem).permit(:origem, :destino, :preco, :dia, :mes, :ano, :Aerotransporte_id)
    end
end

app/helpers/passagems_helper.rb
module PassagemsHelper
end

app/views/passagems/_form.html.erb
<%= form_with(model: passagem, local: true) do |form| %>
  <% if passagem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(passagem.errors.count, "error") %> prohibited this passagem from being saved:</h2>

      <ul>
      <% passagem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :origem %>
    <%= form.text_field :origem %>
  </div>

  <div class="field">
    <%= form.label :destino %>
    <%= form.text_field :destino %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :dia %>
    <%= form.text_field :dia %>
  </div>

  <div class="field">
    <%= form.label :mes %>
    <%= form.text_field :mes %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.text_field :ano %>
  </div>

  <div class="field">
    <%= form.label :Aerotransporte_id %>
 <%= form.collection_select(:Aerotransporte_id, Aerotransporte.all, :id, :nome, prompt: true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/passagems/edit.html.erb
<h1>Editing Passagem</h1>

<%= render 'form', passagem: @passagem %>

<%= link_to 'Show', @passagem %> |
<%= link_to 'Back', passagems_path %>

app/views/passagems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passagens</h1>

<table>
  <thead>
    <tr>
      <th>Origem</th>
      <th>Destino</th>
      <th>Preco</th>
      <th>Dia</th>
      <th>Mes</th>
      <th>Ano</th>
      <th>Aerotransporte</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passagems.each do |passagem| %>
      <tr>
        <td><%= passagem.origem %></td>
        <td><%= passagem.destino %></td>
        <td><%= passagem.preco %></td>
        <td><%= passagem.dia %></td>
        <td><%= passagem.mes %></td>
        <td><%= passagem.ano %></td>
        <td><%= passagem.Aerotransporte.nome %></td>
        <td><%= link_to 'Show', passagem %></td>
        <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_passagem_path(passagem) %></td>
        <td><%= link_to 'Destroy', passagem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if admin_signed_in? %>
<%= link_to 'New Passagem', new_passagem_path %>
<%end%>

app/views/passagems/new.html.erb
<h1>New Passagem</h1>

<%= render 'form', passagem: @passagem %>

<%= link_to 'Back', passagems_path %>

app/views/passagems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origem:</strong>
  <%= @passagem.origem %>
</p>

<p>
  <strong>Destino:</strong>
  <%= @passagem.destino %>
</p>
   <% if user_signed_in? || admin_signed_in?%>
   <%= button_to 'Add to cart', line_items_path(passagem_id: @passagem), class: 'button is-warning add-to-cart' %>
  
  <%end%>
<p>
  <strong>Preco:</strong>
  <%= @passagem.preco %>
</p>

<p>
  <strong>Dia:</strong>
  <%= @passagem.dia %>
</p>

<p>
  <strong>Mes:</strong>
  <%= @passagem.mes %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @passagem.ano %>
</p>

<p>
  <strong>Aerotransporte:</strong>
  <%= @passagem.Aerotransporte.nome %>
</p>

<%= link_to 'Edit', edit_passagem_path(@passagem) %> |
<%= link_to 'Back', passagems_path %>