config/routes.rb
Rails.application.routes.draw do
 
  resources :line_items
  resources :carts
  resources :passagems
  devise_for :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :aerotransportes
  
  root 'aerotransportes#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aerotransporte.rb
class Aerotransporte < ApplicationRecord
    has_many :passagems
end

app/controllers/aerotransportes_controller.rb
class AerotransportesController < ApplicationController
  before_action :set_aerotransporte, only: [:show, :edit, :update, :destroy]

  # GET /aerotransportes
  # GET /aerotransportes.json
  def index
    @aerotransportes = Aerotransporte.all
  end

  # GET /aerotransportes/1
  # GET /aerotransportes/1.json
  def show
  end

  # GET /aerotransportes/new
  def new
    @aerotransporte = Aerotransporte.new
  end

  # GET /aerotransportes/1/edit
  def edit
  end

  # POST /aerotransportes
  # POST /aerotransportes.json
  def create
    @aerotransporte = Aerotransporte.new(aerotransporte_params)

    respond_to do |format|
      if @aerotransporte.save
        format.html { redirect_to @aerotransporte, notice: 'Aerotransporte was successfully created.' }
        format.json { render :show, status: :created, location: @aerotransporte }
      else
        format.html { render :new }
        format.json { render json: @aerotransporte.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aerotransportes/1
  # PATCH/PUT /aerotransportes/1.json
  def update
    respond_to do |format|
      if @aerotransporte.update(aerotransporte_params)
        format.html { redirect_to @aerotransporte, notice: 'Aerotransporte was successfully updated.' }
        format.json { render :show, status: :ok, location: @aerotransporte }
      else
        format.html { render :edit }
        format.json { render json: @aerotransporte.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aerotransportes/1
  # DELETE /aerotransportes/1.json
  def destroy
    @aerotransporte.destroy
    respond_to do |format|
      format.html { redirect_to aerotransportes_url, notice: 'Aerotransporte was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aerotransporte
      @aerotransporte = Aerotransporte.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aerotransporte_params
      params.require(:aerotransporte).permit(:nome)
    end
end

app/helpers/aerotransportes_helper.rb
module AerotransportesHelper
end

app/views/aerotransportes/_form.html.erb
<%= form_with(model: aerotransporte, local: true) do |form| %>
  <% if aerotransporte.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aerotransporte.errors.count, "error") %> prohibited this aerotransporte from being saved:</h2>

      <ul>
      <% aerotransporte.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aerotransportes/edit.html.erb
<% if admin_signed_in? %>
<h1>Editing Aerotransporte</h1>
<%= render 'form', aerotransporte: @aerotransporte %>

<%= link_to 'Show', @aerotransporte %> |
<%= link_to 'Back', aerotransportes_path %>
<%else%>
<h2><h2>Operacao somente permitida para administradores...</h2></h2>

<%end%>

app/views/aerotransportes/index.html.erb
<div class="container">
        <div class="row justify-content-center mb-5">
          <div class="col-md-7">
            <h2 class="font-weight-light text-black text-center">Aerotransportes</h2>
          </div>
        </div>
<p id="notice"><%= notice %></p>

<!--<h1>Aerotransportes</h1>-->

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aerotransportes.each do |aerotransporte| %>
      <tr>
        <td><%= aerotransporte.nome %></td>
        <td><%= link_to 'Show', aerotransporte %></td>
        <% if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_aerotransporte_path(aerotransporte) %></td>
        <td><%= link_to 'Destroy', aerotransporte, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin_signed_in? %>
<%= link_to 'New Aerotransporte', new_aerotransporte_path %>
<%end%>

app/views/aerotransportes/new.html.erb
<% if admin_signed_in? %>
<h1>New Aerotransporte</h1>
<%= render 'form', aerotransporte: @aerotransporte %>

<%= link_to 'Back', aerotransportes_path %>
<%else%>
<h2>Operacao somente permitida para administradores...</h2>
<% end %>

app/views/aerotransportes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aerotransporte.nome %>
</p>

<%= link_to 'Edit', edit_aerotransporte_path(@aerotransporte) %> |
<%= link_to 'Back', aerotransportes_path %>