config/routes.rb
Rails.application.routes.draw do
 
  resources :line_items
  resources :carts
  resources :passagems
  devise_for :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :aerotransportes
  
  root 'aerotransportes#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Viajar.com </title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,700,900|Display+Playfair:200,300,400,700"> 
    <link rel="stylesheet" href="fonts/icomoon/style.css">

    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="css/jquery-ui.css">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">

    <link rel="stylesheet" href="css/bootstrap-datepicker.css">

    <link rel="stylesheet" href="fonts/flaticon/font/flaticon.css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/mediaelement@4.2.7/build/mediaelementplayer.min.css">


    <link rel="stylesheet" href="css/aos.css">

    <link rel="stylesheet" href="css/style.css">
    
  </head>
  <body>
  
  <div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    
    <header class="site-navbar py-1" role="banner">

      <div class="container">
        <div class="row align-items-center">
          
          <div class="col-6 col-xl-2">
            <h1 class="mb-0"><a href="index.html" class="text-black h2 mb-0">Viajar.com</a></h1>
          </div>
          <div class="col-10 col-md-8 d-none d-xl-block">
            <nav class="site-navigation position-relative text-right text-lg-center" role="navigation">

              <ul class="site-menu js-clone-nav mx-auto d-none d-lg-block">
                <li class="active">
                  <a href="index.html">Home</a>
                </li>
                
                <li><a href="discount.html">Passagens</a></li>
                <li><a href="about.html">Sobre os destinos</a></li>
                <li><a href="blog.html">Dicas</a></li>
                <li><a href="/passagems"><span class="glyphicon glyphicon-user"></span> Voos</a></li>
                <li><a href="/aerotransportes"><span class="glyphicon glyphicon-user"></span> AeroTransporte</a></li>
              <li><a href="/carts"><span class="glyphicon glyphicon-user"></span> Carrinho</a></li>
                </ul>
               <!-- <li><a href="contact.html">Contact</a></li>-->
              </ul>
            </nav>
          </div>

          <div class="col-6 col-xl-2 text-right">
            <div class="d-none d-xl-inline-block">
              <ul class="site-menu js-clone-nav ml-auto list-unstyled d-flex text-right mb-0" data-class="social">
                <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        
              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                  <%= button_to 'Exit', destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %> 

             <%if !admin_signed_in?%>
            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>
             <%end%>
            <%end%>

            <% if admin_signed_in? %>
        
              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_admin_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to current_admin.name, edit_admin_registration_path, class:"navbar-item" %>
                  <%= button_to 'Exit', destroy_admin_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %> 
            <%if !user_signed_in?%>
            <%= link_to "Admin?", new_admin_session_path, class:"navbar-item button is-warning" %>
            <%end%>
            <% end %>
    </ul>
                
              </ul>
            </div>

            <div class="d-inline-block d-xl-none ml-md-0 mr-auto py-3" style="position: relative; top: 3px;"><a href="#" class="site-menu-toggle js-menu-toggle text-black"><span class="icon-menu h3"></span></a></div>

          </div>

        </div>
      </div>
      
    </header>
<div class="container">
    <%= yield %>
  </body>
</html>